version: 2
updates:
  - package-ecosystem:huget"
    directory: "/code/"
    schedule:
      interval: "daily"

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
